name = "AtomsCalculators"
uuid = "a3e0e189-c65a-42c1-833c-339540406eb1"
authors = ["JuliaMolSim contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
